django_polling_magic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('polling_magic.urls'), name='polling_magic_urls'),
]

polling_magic/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.PollList.as_view(), name='home'),
    path('home', views.home),
    path('poll/<int:id>/', views.view_poll, name='view_poll'),
    path('like/<int:id>', views.poll_like, name='poll_like'),
    path('dislike/<int:id>', views.poll_dislike, name='poll_dislike'),
    path('accounts/', include('allauth.urls')),
    path(
        'poll/edit/<int:p_id>/<int:c_id>/',
        views.edit_comment, name='edit_comment'),
    path(
        'poll/delete/<int:p_id>/<int:c_id>/',
        views.delete_comment, name='delete_comment'),
]

polling_magic/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Poll(models.Model):
    set = models.CharField(max_length=250, null=False, blank=False)
    slug = models.SlugField(max_length=200, null=False, blank=False)
    image = CloudinaryField('set image', null=False, blank=False)
    new_cards = models.IntegerField(default='0', null=False, blank=False)
    set_icon = CloudinaryField('set icon', null=False, blank=False)
    lore = models.TextField(null=False, blank=False)
    release_date = models.DateField(null=False, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='set_likes', blank=True)
    dislikes = models.ManyToManyField(
        User, related_name='set_dislikes', blank=True)

    def __str__(self):
        return self.set

    def number_of_likes(self):
        return self.likes.count()

    def number_of_dislikes(self):
        return self.dislikes.count()


class Comment(models.Model):
    post = models.ForeignKey(
        Poll, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField(null=False, blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

polling_magic/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

polling_magic/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Poll, Comment
from .forms import CommentForm


def home(request):
    return render(request, 'templates/index')


class PollList(generic.ListView):
    model = Poll
    template_name = 'index.html'
    paginate_by = 6


def view_poll(request, id):
    poll = get_object_or_404(Poll, id=id)
    comments = Comment.objects.filter(post=poll, approved=True)
    if request.method == "POST":
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            comment_form.instance.name = request.user.username
            comment_form.instance.body = request.POST.get("body")
            comment_form.instance.approved = True
            comment_form.instance.post = poll
            comment_form.instance.save()
            messages.success(request, "Comment Added")
        else:
            messages.error(request, "Error: Please Try Again.")
    comment_form = CommentForm()
    template = 'poll.html'
    context = {
        'poll': poll,
        'comments': comments,
        'commented': False,
        'comment_form': comment_form
    }
    return render(request, template, context)


def edit_comment(request, p_id, c_id):
    poll = get_object_or_404(Poll, id=p_id)
    comment = get_object_or_404(Comment, id=c_id)
    comment_form = CommentForm(request.POST or None, instance=comment)
    if comment_form.is_valid():
        comment_form.instance.name = request.user.username
        comment_form.instance.body = request.POST.get("body")
        comment_form.instance.approved = True
        comment_form.instance.post = poll
        comment_form.instance.save()
        messages.success(request, "Comment Updated")
    else:
        messages.error(request, "Error: Please Try Again.")
    return redirect("view_poll", p_id)


def delete_comment(request, p_id, c_id):
    poll = get_object_or_404(Poll, id=p_id)
    comment = get_object_or_404(Comment, id=c_id)
    comment.delete()
    return redirect("view_poll", p_id)


def poll_like(request, id):
    poll = get_object_or_404(Poll, id=id)
    if poll.likes.filter(id=request.user.id).exists():
        poll.likes.remove(request.user)
    else:
        poll.likes.add(request.user)
    return redirect("view_poll", id)


def poll_dislike(request, id):
    poll = get_object_or_404(Poll, id=id)
    if poll.dislikes.filter(id=request.user.id).exists():
        poll.dislikes.remove(request.user)
    else:
        poll.dislikes.add(request.user)
    return redirect("view_poll", id)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Magic: The Polling</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <!-- Nav bar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Magic: The Polling</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
              </li>
              {% endif %}
          </div>
        </div>
      </nav>
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!--Content Goes here-->
        {% endblock content %}
    </main>
</body>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <div class="col-12 mt-3 left">
            <div class="row">
                <ol class="list-group">
                    {% for poll in poll_list %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <img src="{{ poll.set_icon.url }}" alt="" class="list-group-image">
                        <div class="ms-2 me-auto">
                            <a href="{% url 'view_poll' poll.id %}" class="fw-bold">
                                {{ poll.set }}
                            </a>
                            {{ poll.lore|safe }}
                        </div>
                        <span class="badge bg-success rounded-pill">Likes {{ poll.number_of_likes }} <i
                                class="far fa-thumbs-up"></i></span>
                        <span class="badge bg-danger rounded-pill">Dislikes {{ poll.number_of_dislikes }} <i
                                class="far fa-thumbs-down"></i></span>
                    </li>

                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_prvious %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>

    </nav>
    {% endif %}
</div>

{%endblock%}

templates/poll.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row">

        <div class="col-12 mt-3 left">
            <a href="{{ request.META.HTTP_REFERER }}">Go Back</a>
            <div class="row">
                <div class="card-body">
                    <div class="image-container">
                        <img src="{{ poll.image.url }}" alt="" class="card-img-left">
                    </div>
                    <div class="row">
                        <h2 class="card-title">{{ poll.set }}</h2>
                        <p class="author">Poll created by: {{ poll.author }}</p>
                        <p class="card-text text-muted h6">
                            Set Released:
                            {{ poll.release_date }}
                            {% if user.is_authenticated %}
                                <br>
                                <!-- add 'like' -->
                                <a href="{% url 'poll_like' poll.id %}" class="mx-1 fw-bold text-secondary text-decoration-none">
                                    {% if request.user in poll.likes.all %}
                                        <i class="fas fa-thumbs-up"></i>
                                    {% else %}
                                        <i class="far fa-thumbs-up"></i>
                                    {% endif %}
                                </a>
                                {{ poll.number_of_likes }}

                                <!-- add 'dislike' -->
                                <a href="{% url 'poll_dislike' poll.id %}" class="mx-1 fw-bold text-secondary text-decoration-none">
                                    {% if request.user in poll.dislikes.all %}
                                        <i class="fas fa-thumbs-down"></i>
                                    {% else %}
                                        <i class="far fa-thumbs-down"></i>
                                    {% endif %}
                                </a>
                                {{ poll.number_of_dislikes }}

                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <ul class="list-group list-group-flush">
                <!-- existing comments -->
                {% for comment in comments %}
                    <li class="list-group-item">
                        {{ comment.body }}
                        <br>
                        by {{ comment.name }} on {{ comment.created_on|timesince }}
                        <!-- edit/delete buttons only for user's own comments -->
                        {% if request.user.is_authenticated and comment.name|lower == request.user|lower %}

                            <a href="#" data-bs-toggle="modal" data-bs-target="#modalEdit-{{ comment.id }}">Edit</a> |
                            <a href="#" data-bs-toggle="modal" data-bs-target="#modalDelete-{{ comment.id }}">Delete</a>

                            <!-- EDIT modal -->
                            <div class="modal fade" id="modalEdit-{{ comment.id }}" tabindex="-1" aria-labelledby="modalEdit-{{ comment.id }}-Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <!-- edit comment form -->
                                    <form class="modal-content" method="POST" action="{% url 'edit_comment' poll.id comment.id %}">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="modalEdit-{{ comment.id }}-Label">Edit Comment</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            {% csrf_token %}
                                            <textarea name="body" cols="30" rows="10">{{ comment.body }}</textarea>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save</button>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <!-- DELETE modal -->
                            <div class="modal fade" id="modalDelete-{{ comment.id }}" tabindex="-1" aria-labelledby="modalDelete-{{ comment.id }}-Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <!-- delete comment form -->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title text-danger" id="modalDelete-{{ comment.id }}-Label">Delete Comment?</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete this comment?
                                            <br><br>
                                            {{ comment.body }}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                            <a href="{% url 'delete_comment' poll.id comment.id %}" class="btn btn-danger">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </li>
                {% empty %}
                    <li class="list-group-item text-danger">
                        No Comments Yet!
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row">
        <!-- adding a new comment -->
        {% if user.is_authenticated %}
            <div class="col-12 mb-4 mt-3">
                <div class="row">
                    <!-- For later -->
                    {% if commented %}
                        <div class="alert alert-success" role="alert">
                            Your comment is awaiting approval
                        </div>
                    {% else %}
                        <h3>Leave a comment:</h3>
                        <p>Posting as: {{ user.username }}</p>
                        <form method="post" style="margin-top: 1.3em;">
                            {{ comment_form | crispy }}
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>


{% endblock %}